require 'optparse'
require 'fileutils'
require 'open3'

require_relative 'aura/pipe'
require_relative 'aura/environment'
require_relative 'aura/parser'
require_relative 'aura/options'
require_relative 'aura/colors'
require_relative 'aura/console'
