#! /usr/bin/ruby

bin = ENV["HOME"] + "/.config/aura/src/bin/aura"

if Dir[bin].none?
  puts "install your own aura"
  exit 1
end

args = ""
ARGV.each do |arg|
  args << " " << arg
end

exec(bin + args)
