#! /usr/bin/env ruby

# This script runs appropriate AURA instance
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 
# maybe it's inside its own AURA directory
# >>> user@linux ~/test/aura $ ./aura
#
# also might be called from inside another
# >>> user@linux ~/test/aura/src $ aura
#
# otherwise try ~/.config/aura
# >>> user@linux ~ $ aura
# 
# else error


main = "/src/bin/aura"
path = Array.new

# inside it's own
path << __dir__ + main

# inside another
tmp = Dir.pwd
begin
  path << tmp + main
  tmp = File.dirname tmp
end until tmp == "/"

# default AURA
path << ENV["HOME"] + "/.config/aura" + main

# get first valid path
bin = path.find do |i|
  File.file? i
end

# none valid
if bin.nil?
  $stderr.puts "can't find appropriate AURA"
  exit 1
end

# get current arguments
args = ""
ARGV.each do |arg|
  args << " " << arg
end

# execute appropriate AURA
exec(bin + args)
